sonar.projectKey=myapp-devops
sonar.projectName=Application DevOps
sonar.projectVersion=1.0

sonar.sources=app/backend/src,app/frontend/src
sonar.exclusions=**/node_modules/**,**/*.test.js

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=${env.SONAR_TOKEN}